services:
  postgres:
    container_name: dealPostgresDB
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_DB: dealDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    ports:
      - "5435:5432"
  redis:
    image: redis:latest
    container_name: redis-deals
    ports:
      - "26379:6379"
    command: redis-server --requirepass pass
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=pass
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data: