server:
  port: 8085

spring:
  application:
    name: deal-service
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: pass
  datasource:
    url: jdbc:postgresql://localhost:5435/dealDB
    username: root
    password: pass
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
#    drop-first: true

jwt:
  secret: secretkeyPasswordForAuth12312312312313213123123sdfsdf

schedule:
  fixed-delay: 4000

logging:
  level:
    org:
      springframework:
        security: DEBUG